(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by ogino ryo, created 2011-04-05."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "black")
      (background-mode . dark)
      (background-toolbar-color . "#cccccccccccc")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#7a7a7a7a7a7a")
      (cursor-color . "yellow")
      (foreground-color . "White")
      (mouse-color . "sienna1")
      (top-toolbar-shadow-color . "#f5f5f5f5f5f5")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((ac-fuzzy-cursor-color . "red")
      (anything-show-completion-face . highlight)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . link)
      (goto-address-url-mouse-face . highlight)
      (hl-line-face . hl-line)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (org-goto-interface . outline)
      (term-default-bg-color . "MidnightBlue")
      (term-default-fg-color . "Grey")
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (OrangeRed ((t (nil))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (anything-M-x-key-face ((t (:foreground "orange" :underline t))))
     (anything-apt-installed ((t (:foreground "green"))))
     (anything-bmkext-file ((t (:foreground "Deepskyblue2"))))
     (anything-bmkext-gnus ((t (:foreground "magenta"))))
     (anything-bmkext-info ((t (:foreground "green"))))
     (anything-bmkext-man ((t (:foreground "Orange4"))))
     (anything-bmkext-no--file ((t (:foreground "grey"))))
     (anything-bmkext-w3m ((t (:foreground "yellow"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-dired-symlink-face ((t (:foreground "DarkOrange"))))
     (anything-emms-playlist ((t (:foreground "Springgreen4" :underline t))))
     (anything-ffiles-prefix-face ((t (:background "yellow" :foreground "black"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-grep-file ((t (:foreground "BlueViolet" :underline t))))
     (anything-grep-lineno ((t (:foreground "Darkorange1"))))
     (anything-grep-match ((t (:background "RoyalBlue3"))))
     (anything-header ((t (:background "#002" :foreground "cornflower blue"))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-match ((t (:background "RoyalBlue3"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (bbdb-company ((t (nil))))
     (bbdb-field-name ((t (:bold t :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (nil))))
     (blank-tab-face ((t (nil))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :weight bold))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:underline t))))
     (color-mode-face-@ ((t (:foreground "orange"))))
     (color-mode-face-a ((t (:foreground "blue"))))
     (color-mode-face-b ((t (:foreground "red"))))
     (color-mode-face-c ((t (:foreground "green3"))))
     (color-mode-face-d ((t (:background "red" :foreground "white"))))
     (color-mode-face-e ((t (:background "orange" :foreground "blue"))))
     (color-mode-face-f ((t (:background "blue" :foreground "yellow"))))
     (color-mode-face-g ((t (:background "lightblue" :foreground "brown"))))
     (color-mode-face-h ((t (:background "brown" :foreground "white"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:bold t :foreground "sky blue" :weight bold))))
     (compilation-error ((t (:bold t :foreground "Red" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:bold t :foreground "turquoise" :weight bold))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:foreground "sky blue"))))
     (completions-common-part ((t (:stipple nil :background "MidnightBlue" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cperl-array-face ((t (:foreground "darkseagreen"))))
     (cperl-hash-face ((t (:foreground "darkseagreen"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cursor ((t (:background "yellow"))))
     (custom-button-face ((t (:bold t :weight bold))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment-face ((t (:background "gray85"))))
     (custom-comment-tag-face ((t (:foreground "blue4"))))
     (custom-documentation-face ((t (:foreground "light blue"))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:foreground "light blue" :underline t))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (diary-face ((t (:foreground "IndianRed"))))
     (dired-directory ((t (:bold t :foreground "aquamarine" :weight bold))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "forestgreen" :weight bold))))
     (dired-face-executable ((t (:foreground "indianred"))))
     (dired-face-flagged ((t (:background "SlateGray"))))
     (dired-face-marked ((t (:background "darkblue" :foreground "deepskyblue"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "grey95"))))
     (dired-flagged ((t (:bold t :foreground "Red" :weight bold))))
     (dired-header ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "pale green"))))
     (dired-marked ((t (:bold t :foreground "Red" :weight bold))))
     (dired-perm-write ((t (:foreground "light blue"))))
     (dired-symlink ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (dired-warning ((t (:bold t :foreground "Red" :weight bold))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (elscreen-tab-background-face ((t (:background "#3ff83ff83ff8"))))
     (elscreen-tab-control-face ((t (:background "black" :foreground "White"))))
     (elscreen-tab-current-screen-face ((t (:background "black" :foreground "White"))))
     (elscreen-tab-other-screen-face ((t (:background "#1ffc1ffc1ffc" :foreground "#a00ba00ba00b"))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "red" :weight bold))))
     (emacs-wiki-link-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "sandybrown"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "Beige"))))
     (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
     (erc-keyword-face ((t (:bold t :foreground "orange" :weight bold))))
     (erc-notice-face ((t (:foreground "MediumAquamarine"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "sandybrown"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (ffap ((t (:background "dark slate blue" :foreground "light blue"))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cadetblue"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (nil))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (nil))))
     (font-latex-sedate-face ((t (nil))))
     (font-latex-string-face ((t (nil))))
     (font-latex-warning-face ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "light blue"))))
     (font-lock-comment-face ((t (:foreground "IndianRed"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "light sky blue"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-exit-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "YellowGreen"))))
     (font-lock-keyword-face ((t (:foreground "PaleYellow"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "Orange"))))
     (font-lock-type-face ((t (:foreground "Green"))))
     (font-lock-variable-name-face ((t (:foreground "darkseagreen"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "grey95"))))
     (gnu-cite-face-3 ((t (nil))))
     (gnu-cite-face-4 ((t (nil))))
     (gnus-cite-attribution-face ((t (:underline t))))
     (gnus-cite-face-1 ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:bold t :foreground "cadetblue" :weight bold))))
     (gnus-cite-face-3 ((t (:bold t :foreground "gold" :weight bold))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:bold t :foreground "chocolate" :weight bold))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:bold t :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-italic ((t (:underline t))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-header-content-face ((t (:foreground "forest green"))))
     (gnus-header-from-face ((t (:bold t :foreground "spring green" :weight bold))))
     (gnus-header-name-face ((t (:foreground "deep sky blue"))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "purple" :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "orange" :weight bold))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-signature-face ((t (:bold t :foreground "khaki" :weight bold))))
     (gnus-splash ((t (nil))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-low-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-low-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-normal-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:foreground "sky blue"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highlight-cl ((t (:underline "red"))))
     (highlight-cl-and-other ((t (:underline t))))
     (highlight-cl-macro ((t (:underline "steel blue"))))
     (highline-face ((t (:background "SeaGreen"))))
     (hl-line ((t (:background "dark slate blue" :foreground "light blue"))))
     (holiday-face ((t (:background "DimGray"))))
     (html-helper-italic-face ((t (nil))))
     (hyper-apropos-documentation ((t (:foreground "darkred"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "blue4"))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:italic t :bold t :slant italic :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (info-menu-5 ((t (:underline t))))
     (info-node ((t (:bold t :foreground "DodgerBlue1" :underline t :weight bold))))
     (info-xref ((t (:foreground "DodgerBlue1" :underline t))))
     (isearch ((t (:background "blue"))))
     (isearch-fail ((t (:background "red4"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (kai-gnus-cite-face-1 ((t (:foreground "LightCyan4"))))
     (kai-gnus-cite-face-2 ((t (:foreground "LightSkyBlue2"))))
     (kai-gnus-cite-face-3 ((t (:foreground "DodgerBlue3"))))
     (kai-gnus-group-mail-face ((t (:foreground "darkslategrey"))))
     (kai-gnus-group-nonempty-mail-face ((t (:foreground "DarkRed"))))
     (kai-gnus-group-starred-face ((t (:foreground "grey50"))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (nil))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linum ((t (:foreground "red" :height 0.8))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "MidnightBlue" :foreground "Grey"))))
     (message-cited-text ((t (:italic t :slant italic))))
     (message-cited-text-face ((t (:bold t :foreground "green" :weight bold))))
     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold))))
     (message-header-contents ((t (:italic t :slant italic))))
     (message-header-name-face ((t (:bold t :foreground "orange" :weight bold))))
     (message-header-newsgroups-face ((t (:bold t :foreground "violet" :weight bold))))
     (message-header-other-face ((t (:bold t :foreground "chocolate" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "yellow" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "cadetblue" :weight bold))))
     (message-header-xheader-face ((t (:bold t :foreground "light blue" :weight bold))))
     (message-headers ((t (:bold t :weight bold))))
     (message-highlighted-header-contents ((t (:italic t :bold t :slant italic :weight bold))))
     (message-mml-face ((t (:bold t :foreground "Green3" :weight bold))))
     (message-separator-face ((t (:foreground "blue3"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (:background "DarkRed" :foreground "white" :box (:line-width 1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "DarkRed" :foreground "white" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "dark slate blue" :foreground "wheat"))))
     (modeline-mousable ((t (:background "DarkRed" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "DarkRed" :foreground "white"))))
     (mouse ((t (:background "sienna1"))))
     (my-igface ((t (:background "paleturquoise"))))
     (next-error ((t (:background "DarkSlateBlue"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-agenda-clocking ((t (:background "steel blue"))))
     (org-agenda-column-dateline ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 97 :family "DejaVu Sans Mono"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-checkbox-statistics-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 97 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "aquamarine" :weight bold))))
     (org-level-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (org-level-3 ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-level-4 ((t (:foreground "light blue"))))
     (org-level-5 ((t (:bold t :foreground "sky blue" :weight bold))))
     (org-level-6 ((t (:foreground "pale green"))))
     (org-level-7 ((t (:foreground "aquamarine"))))
     (org-level-8 ((t (:foreground "light sky blue"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-meta-line ((t (:foreground "light blue"))))
     (org-mode-line-clock ((t (:background "slate blue" :foreground "wheat" :box (:line-width -1 :style released-button)))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:bold t :foreground "Red" :weight bold))))
     (outline-1 ((t (:bold t :foreground "aquamarine" :weight bold))))
     (outline-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (outline-3 ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (outline-4 ((t (:foreground "light blue"))))
     (outline-5 ((t (:bold t :foreground "sky blue" :weight bold))))
     (outline-6 ((t (:foreground "pale green"))))
     (outline-7 ((t (:foreground "aquamarine"))))
     (outline-8 ((t (:foreground "light sky blue"))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:foreground "red"))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "red" :foreground "white"))))
     (paren-mismatch ((t (:background "DeepPink"))))
     (paren-mismatch-face ((t (:bold t :weight bold))))
     (paren-no-match-face ((t (:bold t :weight bold))))
     (pointer ((t (:foreground "blue"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (primary-selection ((t (:background "blue"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "slate blue"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "blue"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (semantic-dirty-token-face ((t (:background "lightyellow"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "red"))))
     (sgml-end-tag-face ((t (:foreground "blue"))))
     (sgml-entity-face ((t (:foreground "magenta"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "green"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-start-tag-face ((t (:foreground "blue"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-option-face ((t (:foreground "blue"))))
     (shell-output-2-face ((t (:foreground "darkseagreen"))))
     (shell-output-3-face ((t (:foreground "slategrey"))))
     (shell-output-face ((t (:foreground "palegreen"))))
     (shell-prompt-face ((t (:foreground "red"))))
     (show-paren-match ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch ((t (:background "Red" :foreground "White"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-face ((t (:background "dark slate blue" :foreground "light blue" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :foreground "Red" :weight bold))))
     (slime-inspector-label-face ((t (:foreground "pale green"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (slime-inspector-value-face ((t (:foreground "aquamarine"))))
     (slime-note-face ((t (:underline "light goldenrod"))))
     (slime-reader-conditional-face ((t (:foreground "light blue"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:foreground "light sky blue"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "gold"))))
     (slime-warning-face ((t (:underline "coral"))))
     (speedbar-button-face ((t (:bold t :foreground "green4" :weight bold))))
     (speedbar-directory-face ((t (:bold t :foreground "blue4" :weight bold))))
     (speedbar-file-face ((t (:bold t :foreground "cyan4" :weight bold))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (swbuff-current-buffer-face ((t (:bold t :weight bold))))
     (tabbar-button ((t (:background "gray50" :foreground "grey75" :box (:line-width 1 :color "white" :style released-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-button-highlight ((t (:background "gray50" :foreground "grey75" :height 0.8 :family "Sans Serif"))))
     (tabbar-default ((t (:background "gray50" :foreground "grey75" :height 0.8 :family "Sans Serif"))))
     (tabbar-highlight ((t (:underline t))))
     (tabbar-selected ((t (:background "gray50" :foreground "blue" :box (:line-width 1 :color "white" :style pressed-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-separator ((t (:background "gray50" :foreground "grey75" :height 0.8 :family "Sans Serif"))))
     (tabbar-unselected ((t (:background "gray50" :foreground "grey75" :box (:line-width 1 :color "white" :style released-button) :height 0.8 :family "Sans Serif"))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-green ((t (:foreground "green"))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellowbg ((t (:background "yellow"))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (tool-bar ((t (:background "Gray80" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline nil))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (nil))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "Gray80"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray" :foreground "wheat"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray" :foreground "wheat"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:background "white"))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "snow" :foreground "blue")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))