(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by ogino ryo, created 2011-04-05."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#102e4e")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "green")
      (foreground-color . "#eeeeee")
      (mouse-color . "white")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((ac-fuzzy-cursor-color . "red")
      (anything-show-completion-face . highlight)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . secondary-selection)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . info-xref)
      (compilation-message-face . underline)
      (display-time-mail-face . mode-line)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (hl-line-face . hl-line)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . secondary-selection)
      (org-goto-interface . outline)
      (term-default-bg-color . "MidnightBlue")
      (term-default-fg-color . "Grey")
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#102e4e" :foreground "#eeeeee" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (Buffer-menu-buffer-face ((t (:bold t :weight bold))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (OrangeRed ((t (nil))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (antlr-font-lock-keyword-face ((t (:bold t :foreground "black" :weight bold))))
     (antlr-font-lock-literal-face ((t (:bold t :foreground "brown4" :weight bold))))
     (antlr-font-lock-ruledef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-ruleref-face ((t (:foreground "blue4"))))
     (antlr-font-lock-tokendef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-tokenref-face ((t (:foreground "orange4"))))
     (anything-M-x-key-face ((t (:foreground "orange" :underline t))))
     (anything-apt-installed ((t (:foreground "green"))))
     (anything-bmkext-file ((t (:foreground "Deepskyblue2"))))
     (anything-bmkext-gnus ((t (:foreground "magenta"))))
     (anything-bmkext-info ((t (:foreground "green"))))
     (anything-bmkext-man ((t (:foreground "Orange4"))))
     (anything-bmkext-no--file ((t (:foreground "grey"))))
     (anything-bmkext-w3m ((t (:foreground "yellow"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-dired-symlink-face ((t (:foreground "DarkOrange"))))
     (anything-emms-playlist ((t (:foreground "Springgreen4" :underline t))))
     (anything-ffiles-prefix-face ((t (:background "yellow" :foreground "black"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-grep-file ((t (:foreground "BlueViolet" :underline t))))
     (anything-grep-lineno ((t (:foreground "Darkorange1"))))
     (anything-grep-match ((t (:background "RoyalBlue3"))))
     (anything-header ((t (:background "#002" :foreground "cornflower blue"))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-match ((t (:background "RoyalBlue3"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :weight bold))))
     (bbdb-field-value ((t (:foreground "dark sea green"))))
     (bbdb-name ((t (:underline t))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "green" :foreground "black"))))
     (blue ((t (:bold t :foreground "blue" :weight bold))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (border-glyph ((t (:bold t :weight bold))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:background "blue"))))
     (change-log-acknowledgement-face ((t (:italic t :foreground "CadetBlue" :slant italic))))
     (change-log-conditionals-face ((t (:foreground "SeaGreen2"))))
     (change-log-date-face ((t (:foreground "burlywood"))))
     (change-log-email-face ((t (:foreground "SeaGreen2"))))
     (change-log-file-face ((t (:bold t :foreground "goldenrod" :weight bold))))
     (change-log-function-face ((t (:foreground "SeaGreen2"))))
     (change-log-list-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
     (change-log-name-face ((t (:foreground "gold"))))
     (clear-case-mode-string-face ((t (:bold t :background "grey" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :weight bold :height 0.9 :family "Arial"))))
     (clearcase-dired-checkedout-face ((t (:foreground "red"))))
     (cmode-bracket-face ((t (:bold t :weight bold))))
     (color-mode-face-@ ((t (:foreground "orange"))))
     (color-mode-face-a ((t (:foreground "blue"))))
     (color-mode-face-b ((t (:foreground "red"))))
     (color-mode-face-c ((t (:foreground "green3"))))
     (color-mode-face-d ((t (:background "red" :foreground "white"))))
     (color-mode-face-e ((t (:background "orange" :foreground "blue"))))
     (color-mode-face-f ((t (:background "blue" :foreground "yellow"))))
     (color-mode-face-g ((t (:background "lightblue" :foreground "brown"))))
     (color-mode-face-h ((t (:background "brown" :foreground "white"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:bold t :foreground "sky blue" :weight bold))))
     (compilation-error ((t (:bold t :foreground "Red" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:bold t :foreground "turquoise" :weight bold))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:foreground "sky blue"))))
     (completions-common-part ((t (:stipple nil :background "MidnightBlue" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (:bold t :foreground "maroon" :weight bold))))
     (cparen-around-begin-face ((t (:foreground "maroon"))))
     (cparen-around-conditional-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (cparen-around-define-face ((t (:bold t :foreground "Blue" :weight bold))))
     (cparen-around-lambda-face ((t (:foreground "LightSeaGreen"))))
     (cparen-around-letdo-face ((t (:bold t :foreground "LightSeaGreen" :weight bold))))
     (cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
     (cparen-around-set!-face ((t (:foreground "OrangeRed"))))
     (cparen-around-syntax-rules-face ((t (:foreground "Magenta"))))
     (cparen-around-vector-face ((t (:foreground "chocolate"))))
     (cparen-binding-face ((t (:foreground "ForestGreen"))))
     (cparen-binding-list-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (cparen-conditional-clause-face ((t (:foreground "RoyalBlue"))))
     (cparen-normal-paren-face ((t (:foreground "grey50"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-here-face ((t (:background "gray68" :foreground "DeepPink"))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cperl-pod-face ((t (nil))))
     (cperl-pod-head-face ((t (nil))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "green" :foreground "black"))))
     (custom-button-face ((t (:bold t :weight bold))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:bold t :background "blue" :foreground "white" :weight bold))))
     (custom-comment-face ((t (:foreground "white"))))
     (custom-comment-tag-face ((t (:foreground "white"))))
     (custom-documentation-face ((t (:bold t :weight bold))))
     (custom-face-tag-face ((t (:bold t :underline t :weight bold))))
     (custom-group-tag-face ((t (:bold t :foreground "DarkBlue" :underline t :weight bold))))
     (custom-group-tag-face-1 ((t (:bold t :foreground "red" :underline t :weight bold))))
     (custom-invalid-face ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (custom-modified-face ((t (:bold t :background "blue" :foreground "white" :weight bold))))
     (custom-rogue-face ((t (:bold t :background "black" :foreground "pink" :weight bold))))
     (custom-saved-face ((t (:bold t :underline t :weight bold))))
     (custom-set-face ((t (:bold t :background "white" :foreground "blue" :weight bold))))
     (custom-state-face ((t (:bold t :foreground "dark green" :weight bold))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:bold t :foreground "blue" :underline t :weight bold))))
     (cvs-filename-face ((t (:foreground "lightblue"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (:foreground "cyan"))))
     (date ((t (:foreground "green"))))
     (diary-face ((t (:foreground "orange red"))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "grey70"))))
     (diff-file-header-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-function-face ((t (:foreground "grey70"))))
     (diff-header-face ((t (:background "grey45"))))
     (diff-hunk-header-face ((t (:background "grey45"))))
     (diff-index-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-nonexistent-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-removed-face ((t (nil))))
     (dired-directory ((t (:bold t :foreground "aquamarine" :weight bold))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :weight bold))))
     (dired-face-executable ((t (:foreground "SeaGreen"))))
     (dired-face-flagged ((t (:background "LightSlateGray"))))
     (dired-face-header ((t (:background "grey75" :foreground "black"))))
     (dired-face-marked ((t (:background "PaleVioletRed"))))
     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "cyan"))))
     (dired-flagged ((t (:bold t :foreground "Red" :weight bold))))
     (dired-header ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "pale green"))))
     (dired-marked ((t (:bold t :foreground "Red" :weight bold))))
     (dired-perm-write ((t (:foreground "light blue"))))
     (dired-symlink ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (dired-warning ((t (:bold t :foreground "Red" :weight bold))))
     (display-time-mail-balloon-enhance-face ((t (:bold t :background "orange" :weight bold))))
     (display-time-mail-balloon-gnus-group-face ((t (:bold t :foreground "blue" :weight bold))))
     (display-time-time-balloon-face ((t (:bold t :foreground "red" :weight bold))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class-face ((t (:foreground "purple"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class-face ((t (:bold t :foreground "blue" :weight bold))))
     (ebrowse-tree-mark-face ((t (:foreground "red"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (edb-inter-field-face ((t (:foreground "deep sky blue"))))
     (edb-normal-summary-face ((t (:foreground "gold"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (elscreen-tab-background-face ((t (:background "#4ff86df88df8"))))
     (elscreen-tab-control-face ((t (:background "#102e4e" :foreground "#eeeeee"))))
     (elscreen-tab-current-screen-face ((t (:background "#102e4e" :foreground "#eeeeee"))))
     (elscreen-tab-other-screen-face ((t (:background "#2ffc4dfc6dfc" :foreground "#8e0c8e0c8e0c"))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "coral" :underline "coral" :weight bold))))
     (emacs-wiki-link-face ((t (:bold t :foreground "cyan" :underline "cyan" :weight bold))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :weight bold))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-host-danger-face ((t (:foreground "red"))))
     (erc-input-face ((t (:foreground "light blue"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-keyword-face ((t (:bold t :foreground "orange" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight semi-bold))))
     (erc-nick-msg-face ((t (:foreground "#888"))))
     (erc-notice-face ((t (:foreground "light salmon"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :foreground "light blue" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-readonly-face ((t (:foreground "Brown"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "DarkCyan" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "Grey30"))))
     (eshell-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (extra-whitespace-face ((t (:background "pale green"))))
     (face-1 ((t (:stipple nil :foreground "royal blue" :family "andale mono"))))
     (face-2 ((t (:stipple nil :foreground "DeepSkyBlue1" :overline nil :underline nil :slant normal :foundry "outline" :family "andale mono"))))
     (face-3 ((t (:stipple nil :foreground "NavajoWhite3"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (ffap ((t (:background "dark slate blue" :foreground "light blue"))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "fixed"))))
     (fl-comment-face ((t (:foreground "medium purple"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "green"))))
     (fl-keyword-face ((t (:foreground "LightGreen"))))
     (fl-string-face ((t (:foreground "light coral"))))
     (fl-type-face ((t (:foreground "cyan"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "OliveDrab" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "OliveDrab" :slant italic))))
     (font-latex-math-face ((t (:foreground "burlywood"))))
     (font-latex-sedate-face ((t (:foreground "LightGray"))))
     (font-latex-string-face ((t (:foreground "LightSalmon"))))
     (font-latex-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightCoral"))))
     (font-lock-comment-delimiter-face ((t (:foreground "light blue"))))
     (font-lock-comment-face ((t (:italic t :foreground "CadetBlue" :slant italic))))
     (font-lock-constant-face ((t (:foreground "gold"))))
     (font-lock-doc-face ((t (:foreground "BlanchedAlmond"))))
     (font-lock-doc-string-face ((t (:foreground "BlanchedAlmond"))))
     (font-lock-emphasized-face ((t (:bold t :weight bold))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "goldenrod" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (:italic t :bold t :slant italic :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "DarkBlue" :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "gold"))))
     (font-lock-reference-face ((t (:foreground "LightCoral"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-special-comment-face ((t (:foreground "blue4"))))
     (font-lock-special-keyword-face ((t (:foreground "red4"))))
     (font-lock-string-face ((t (:foreground "burlywood"))))
     (font-lock-type-face ((t (:foreground "CadetBlue1"))))
     (font-lock-variable-name-face ((t (:foreground "SeaGreen2"))))
     (font-lock-warning-face ((t (:foreground "yellow"))))
     (fringe ((t (:background "#405060"))))
     (gdb-arrow-face ((t (:bold t :weight bold))))
     (gnu-cite-face-3 ((t (nil))))
     (gnu-cite-face-4 ((t (nil))))
     (gnus-cite-attribution-face ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-cite-face-1 ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-cite-face-3 ((t (:bold t :foreground "dark green" :weight bold))))
     (gnus-cite-face-4 ((t (:foreground "OrangeRed"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:bold t :foreground "dark violet" :weight bold))))
     (gnus-cite-face-7 ((t (:foreground "SteelBlue4"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "ForestGreen"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "indianred4" :slant italic))))
     (gnus-header-from-face ((t (:bold t :foreground "red3" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "maroon" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "MidnightBlue" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "red4" :weight bold))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight semi-bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight semi-bold))))
     (gnus-signature-face ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread-face ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :bold t :foreground "firebrick" :slant italic :weight bold))))
     (gnus-summary-low-undownloaded-face ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-normal-undownloaded-face ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:bold t :foreground "green" :weight bold))))
     (gui-button-face ((t (:bold t :background "grey75" :foreground "black" :weight bold))))
     (gui-element ((t (:bold t :background "Gray80" :weight bold))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:foreground "sky blue"))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "yellow"))))
     (highlight ((t (:background "darkgreen"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highlight-cl ((t (:underline "red"))))
     (highlight-cl-and-other ((t (:underline t))))
     (highlight-cl-macro ((t (:underline "steel blue"))))
     (highline-face ((t (:background "black" :foreground "white"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (hl-line ((t (:background "dark slate blue" :foreground "light blue"))))
     (holiday-face ((t (:foreground "green"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (hproperty:but-face ((t (:bold t :weight bold))))
     (hproperty:flash-face ((t (:bold t :weight bold))))
     (hproperty:highlight-face ((t (:bold t :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (:bold t :weight bold))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "blue3" :underline t))))
     (html-helper-italic-face ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t (:bold t :weight bold))))
     (hyper-apropos-documentation ((t (:foreground "white"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "red"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-indicator-face ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (info-header-node ((t (:foreground "DeepSkyBlue1"))))
     (info-header-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
     (info-menu-5 ((t (:foreground "wheat"))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-node ((t (:foreground "DeepSkyBlue1"))))
     (info-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (ispell-face ((t (:bold t :weight bold))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (kai-gnus-cite-face-1 ((t (:foreground "LightCyan4"))))
     (kai-gnus-cite-face-2 ((t (:foreground "LightSkyBlue2"))))
     (kai-gnus-cite-face-3 ((t (:foreground "DodgerBlue3"))))
     (kai-gnus-group-mail-face ((t (:foreground "darkslategrey"))))
     (kai-gnus-group-nonempty-mail-face ((t (:foreground "DarkRed"))))
     (kai-gnus-group-starred-face ((t (:foreground "grey50"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (:bold t :weight bold))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linum ((t (:foreground "red" :height 0.8))))
     (list-mode-item-selected ((t (:bold t :background "gray68" :weight bold))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message-face ((t (:foreground "light salmon"))))
     (m4-face ((t (:background "gray90" :foreground "orange3"))))
     (magenta ((t (:foreground "magenta"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (:bold t :weight bold))))
     (man-heading ((t (:bold t :weight bold))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "gray" :foreground "black" :family "helvetica"))))
     (message-cited-text ((t (:bold t :foreground "orange" :weight bold))))
     (message-cited-text-face ((t (:bold t :foreground "red" :weight bold))))
     (message-header-cc-face ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-contents ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (message-header-name-face ((t (:bold t :foreground "cornflower blue" :weight bold))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other-face ((t (:bold t :foreground "steel blue" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader-face ((t (:bold t :foreground "blue" :weight bold))))
     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :weight bold))))
     (message-mml-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (message-separator-face ((t (:foreground "brown"))))
     (message-url ((t (:bold t :foreground "pink" :weight bold))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (mode-line ((t (:bold t :background "gray" :foreground "black" :box (:line-width 2 :style released-button) :underline t :weight bold))))
     (mode-line-buffer-id ((t (:bold t :background "gray" :foreground "black" :box (:line-width 2 :style released-button) :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline-mousable ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (modeline-mousable-minor-mode ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (mouse ((t (:background "white"))))
     (mpg123-face-cur ((t (:background "#004080" :foreground "yellow"))))
     (mpg123-face-slider ((t (:background "yellow" :foreground "black"))))
     (my-igface ((t (:background "paleturquoise"))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (my-url-face ((t (:foreground "PaleTurquoise"))))
     (next-error ((t (:background "DarkSlateBlue"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-agenda-clocking ((t (:background "steel blue"))))
     (org-agenda-column-dateline ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 97 :family "DejaVu Sans Mono"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-checkbox-statistics-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 97 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "aquamarine" :weight bold))))
     (org-level-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (org-level-3 ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-level-4 ((t (:foreground "light blue"))))
     (org-level-5 ((t (:bold t :foreground "sky blue" :weight bold))))
     (org-level-6 ((t (:foreground "pale green"))))
     (org-level-7 ((t (:foreground "aquamarine"))))
     (org-level-8 ((t (:foreground "light sky blue"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-meta-line ((t (:foreground "light blue"))))
     (org-mode-line-clock ((t (:background "slate blue" :foreground "wheat" :box (:line-width -1 :style released-button)))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:bold t :foreground "Red" :weight bold))))
     (outline-1 ((t (:bold t :foreground "aquamarine" :weight bold))))
     (outline-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (outline-3 ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (outline-4 ((t (:foreground "light blue"))))
     (outline-5 ((t (:bold t :foreground "sky blue" :weight bold))))
     (outline-6 ((t (:foreground "pale green"))))
     (outline-7 ((t (:foreground "aquamarine"))))
     (outline-8 ((t (:foreground "light sky blue"))))
     (overlay-empty-face ((t (nil))))
     (p4-depot-added-face ((t (:foreground "steelblue1"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey90"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:bold t :weight bold))))
     (p4-diff-file-face ((t (:background "blue"))))
     (p4-diff-head-face ((t (:background "blue"))))
     (p4-diff-ins-face ((t (:foreground "steelblue1"))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-blink-on ((t (:foreground "purple"))))
     (paren-face ((t (:background "black" :foreground "darkgreen"))))
     (paren-face-match ((t (:background "black" :foreground "springgreen"))))
     (paren-face-mismatch ((t (:background "black" :foreground "#00CC00" :strike-through t))))
     (paren-face-no-match ((t (:background "black" :foreground "red"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
     (paren-mismatch-face ((t (:bold t :background "DeepPink" :foreground "white" :weight bold))))
     (paren-no-match-face ((t (:bold t :background "yellow" :foreground "white" :weight bold))))
     (pointer ((t (:bold t :weight bold))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (primary-selection ((t (:bold t :background "gray65" :weight bold))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "slate blue"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:bold t :foreground "red" :weight bold))))
     (region ((t (:background "DarkCyan"))))
     (right-margin ((t (:bold t :weight bold))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (nil))))
     (ruler-mode-column-number-face ((t (:stipple nil :background "grey76" :foreground "black" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-current-column-face ((t (:bold t :stipple nil :background "grey76" :foreground "yellow" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-default-face ((t (:stipple nil :background "grey76" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-fill-column-face ((t (:stipple nil :background "grey76" :foreground "red" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-margins-face ((t (:stipple nil :background "grey64" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-tab-stop-face ((t (:stipple nil :background "grey76" :foreground "steelblue" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (scroll-bar ((t (:background "gray" :foreground "#506070"))))
     (searchm-buffer ((t (:bold t :weight bold))))
     (searchm-button ((t (:bold t :weight bold))))
     (searchm-field ((t (nil))))
     (searchm-field-label ((t (:bold t :weight bold))))
     (searchm-highlight ((t (:bold t :weight bold))))
     (secondary-selection ((t (:background "yellow" :foreground "gray10"))))
     (semantic-dirty-token-face ((t (:background "lightyellow"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (setnu-line-number-face ((t (:italic t :bold t :slant italic :weight bold))))
     (sgml-comment-face ((t (:foreground "dark green"))))
     (sgml-doctype-face ((t (:foreground "maroon"))))
     (sgml-end-tag-face ((t (:foreground "blue2"))))
     (sgml-entity-face ((t (:foreground "red2"))))
     (sgml-ignored-face ((t (:background "gray90" :foreground "maroon"))))
     (sgml-ms-end-face ((t (:foreground "maroon"))))
     (sgml-ms-start-face ((t (:foreground "maroon"))))
     (sgml-pi-face ((t (:foreground "maroon"))))
     (sgml-sgml-face ((t (:foreground "maroon"))))
     (sgml-short-ref-face ((t (:foreground "goldenrod"))))
     (sgml-shortref-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-start-tag-face ((t (:foreground "blue2"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-input-face ((t (:bold t :weight bold))))
     (shell-option-face ((t (:bold t :foreground "blue4" :weight bold))))
     (shell-output-2-face ((t (:bold t :foreground "green4" :weight bold))))
     (shell-output-3-face ((t (:bold t :foreground "green4" :weight bold))))
     (shell-output-face ((t (:bold t :weight bold))))
     (shell-prompt-face ((t (:bold t :foreground "red4" :weight bold))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match ((t (:bold t :background "light slate blue" :foreground "yellow" :weight bold))))
     (show-paren-mismatch ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-face ((t (:background "dark slate blue" :foreground "light blue" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :foreground "Red" :weight bold))))
     (slime-inspector-label-face ((t (:foreground "pale green"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (slime-inspector-value-face ((t (:foreground "aquamarine"))))
     (slime-note-face ((t (:underline "light goldenrod"))))
     (slime-reader-conditional-face ((t (:foreground "light blue"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:foreground "light sky blue"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "gold"))))
     (slime-warning-face ((t (:underline "coral"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "blue"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (special-string-face ((t (:foreground "light green"))))
     (speedbar-button-face ((t (:bold t :foreground "magenta" :weight bold))))
     (speedbar-directory-face ((t (:bold t :foreground "orchid" :weight bold))))
     (speedbar-file-face ((t (:bold t :foreground "pink" :weight bold))))
     (speedbar-highlight-face ((t (:background "black"))))
     (speedbar-selected-face ((t (:foreground "cyan" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (tabbar-button ((t (:background "gray50" :foreground "grey75" :box (:line-width 1 :color "white" :style released-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-button-face ((t (:background "black" :foreground "#00cc00" :box (:line-width 2 :color "black" :style released-button)))))
     (tabbar-button-highlight ((t (:background "gray50" :foreground "grey75" :height 0.8 :family "Sans Serif"))))
     (tabbar-default ((t (:background "gray50" :foreground "grey75" :height 0.8 :family "Sans Serif"))))
     (tabbar-default-face ((t (:background "black" :foreground "#00cc00"))))
     (tabbar-highlight ((t (:underline t))))
     (tabbar-selected ((t (:background "gray50" :foreground "blue" :box (:line-width 1 :color "white" :style pressed-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-selected-face ((t (:background "black" :foreground "springgreen" :box (:line-width 2 :color "black" :style released-button)))))
     (tabbar-separator ((t (:background "gray50" :foreground "grey75" :height 0.8 :family "Sans Serif"))))
     (tabbar-separator-face ((t (:background "black" :foreground "#00cc00"))))
     (tabbar-unselected ((t (:background "gray50" :foreground "grey75" :box (:line-width 1 :color "white" :style released-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-unselected-face ((t (:background "black" :foreground "seagreen" :box (:line-width 2 :color "black" :style pressed-button)))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (:bold t :background "snow2" :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:background "snow2" :foreground "blue" :underline t))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyan-bold-face ((t (:bold t :background "snow2" :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:background "snow2" :foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-bg ((t (:foreground "#CCBB77"))))
     (term-default-bg-inv ((t (:foreground "#CCBB77"))))
     (term-default-bold-face ((t (:bold t :background "snow2" :foreground "darkslategray" :weight bold))))
     (term-default-face ((t (:background "snow2" :foreground "darkslategray"))))
     (term-default-fg ((t (:background "#000055"))))
     (term-default-fg-inv ((t (:background "#000055"))))
     (term-default-inv-face ((t (:background "darkslategray" :foreground "snow2"))))
     (term-default-ul-face ((t (:background "snow2" :foreground "darkslategray" :underline t))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (:bold t :background "snow2" :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:background "snow2" :foreground "green" :underline t))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (:foreground "#CCBB77"))))
     (term-invisible-inv ((t (:foreground "#CCBB77"))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (:bold t :background "snow2" :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:background "snow2" :foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (:bold t :background "snow2" :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:background "snow2" :foreground "red" :underline t))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-white-bold-face ((t (:bold t :background "snow2" :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (:background "snow2"))))
     (term-white-ul-face ((t (:background "snow2" :foreground "white" :underline t))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellow-bold-face ((t (:bold t :background "snow2" :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:background "snow2" :foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "yellow"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:bold t :background "Red3" :foreground "gray80" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#102e4e"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:bold t :background "Gray80" :weight bold))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-generic-/constant-face ((t (:foreground "Gold3"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (:foreground "ForestGreen"))))
     (vhdl-font-lock-variable-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (:foreground "Orchid4"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "gray80" :slant italic))))
     (vm-header-from-face ((t (:italic t :background "#65889C" :foreground "cyan" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "black"))))
     (vmpc-pre-sig-face ((t (:foreground "forestgreen"))))
     (vmpc-sig-face ((t (:foreground "steelblue"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (white ((t (:foreground "white"))))
     (widget ((t (:background "Gray80" :foreground "black"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray" :foreground "wheat"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray" :foreground "wheat"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:bold t :background "white" :foreground "black" :weight bold))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (:bold t :weight bold))))
     (x-symbol-info-face ((t (nil))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (nil))))
     (xrdb-option-name-face ((t (:foreground "red"))))
     (xrdb-option-value-face ((t (:bold t :foreground "magenta" :weight bold))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yellow ((t (:bold t :foreground "yellow" :weight bold))))
     (zmacs-region ((t (:bold t :background "gray65" :weight bold)))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))