(source gnu)
(source melpa)

(depends-on "auto-async-byte-compile")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "color-moccur")
(depends-on "dash")
(depends-on "deferred")
(depends-on "direx")
(depends-on "drag-stuff")
(depends-on "e2wm")
(depends-on "eldoc-extension")
(depends-on "emmet-mode")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-haskell")
(depends-on "haml-mode")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-gtags")
(depends-on "helm-ls-git")
(depends-on "helm-projectile")
(depends-on "lispxmp")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "open-junk-file")
(depends-on "paredit")
(depends-on "popup")
(depends-on "popwin")
(depends-on "pretty-lambdada")
(depends-on "projectile")
(depends-on "quickrun")
(depends-on "rainbow-delimiters")
(depends-on "redo+")
(depends-on "s")
(depends-on "smartparens")
(depends-on "solarized-theme")
(depends-on "wrap-region")
(depends-on "yasnippet")
;; (depends-on "ruby-end")
;; ;; (depends-on "ruby-electric")

;; clojure
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "ac-nrepl")
(depends-on "clojure-cheatsheet")
(depends-on "clojure-test-mode")
(depends-on "slamhound")

(development
 (depends-on "el-mock")
 (depends-on "ecukes")
 (depends-on "ert-runner"))
