(source gnu)
(source melpa)

;; (depends-on "auto-complete")
;; (depends-on "cask")
(depends-on "dash")
;; (depends-on "drag-stuff")
;; (depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-haskell")
(depends-on "clojure-mode")
(depends-on "coffee-mode")
(depends-on "color-moccur")
(depends-on "deferred")
(depends-on "direx")
(depends-on "e2wm")
(depends-on "eldoc-extension")
(depends-on "emmet-mode")
(depends-on "expand-region")
(depends-on "haml-mode")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-gtags")
(depends-on "helm-ls-git")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "popup")
(depends-on "popwin")
(depends-on "pretty-lambdada")
(depends-on "s")
(depends-on "smartparens")
(depends-on "quickrun")
(depends-on "redo+")
(depends-on "ruby-electric")
(depends-on "ruby-end")
(depends-on "solarized-theme")
(depends-on "wrap-region")
(depends-on "yasnippet")

(development
 (depends-on "el-mock")
 (depends-on "ecukes")
 (depends-on "ert-runner"))
